twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_horizontal_layout.html.twig'
       # - bootstrap_3_horizontal_layout.html.twig
    date:
        format: "d-m-y"
        #detailed_format: "d-m-Y H:i:s"
        #timezone: "America/Argentina/Tucuman"
        timezone: "Europe/Madrid"
    #money:
    #    currency: 'ARS'
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
